gsb_android_homepage:
    path:     /
    defaults: { _controller: GsbAndroidBundle:Default:index }
gsb_connexion:
    path:     /connexion/{login}/{mdp}
    defaults: { _controller: GsbAndroidBundle:Default:getUnVisiteur }
    
gsb_ListePraticien:
    path:    /listePraticien
    defaults: { _controller: GsbAndroidBundle:Default:getLesPraticiens }

    
gsb_ListePraticienParVisiteur:
    path:   /listePraticienParVisiteur/{matricule}
    defaults: { _controller: GsbAndroidBundle:Default:getLesPraticiensParVisiteur}
    
gsb_DateRV:
    path: /getUneDate/{matricule}
    defaults: { _controller: GsbAndroidBundle:Default:getUneDate }

gsb_ConsulterUnCR:
    path:   /getUnRV/{matricule}/{date}
    defaults: { _controller: GsbAndroidBundle:Default:getUnRV }
    
gsb_AjouterRV:
    path:   /addUnRV
    defaults: { _controller: GsbAndroidBundle:Default:addUnRV }